http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: ['/api','/api/*']
  read:
    host: localhost
    paths: ['/read','/read/*']
  write:
    host: localhost
    paths: ['/write','/write/*']
  stream:
    host: localhost
    paths: ['/stream','/stream/*']
serviceEndpoints:
  server:
    url: 'http://localhost:8000'
  readService:
    url: 'http://localhost:8001'
  writeService:
    url: 'http://localhost:8002'
  streamService:
    url: 'http://localhost:8003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - auth
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: server 
              changeOrigin: true
  readPipeline:
    apiEndpoints:
      - read
    policies:
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: readService
              changeOrigin: true
  writePipeline:
    apiEndpoints:
      - read
    policies:
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: writeService
              changeOrigin: true
  streamPipeline:
    apiEndpoints:
      - stream
    policies:
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: streamService
              changeOrigin: true
