http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  read:
    host: localhost
    paths: ['/read','/read/*']
  write:
    host: localhost
    paths: ['/write','/write/*']
  admin:
    host: localhost
    paths: ['/admin','/admin/*']
  stream:
    host: localhost
    paths: ['/stream','/stream/*']
serviceEndpoints:
  readService:
    url: 'http://localhost:8001'
  writeService:
    url: 'http://localhost:8002'
  adminService:
    url: 'http://localhost:8002'
  streamService:
    url: 'http://localhost:8003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - auth
  - admin
pipelines:
  default:
    apiEndpoints:
      - read
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: readService 
              changeOrigin: true
  writePipeline:
    apiEndpoints:
      - write
    policies:
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: writeService
              changeOrigin: true
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
      - cors:
        - action:
            origin:  '*'
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
      - admin:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true
  streamPipeline:
    apiEndpoints:
      - stream
    policies:
      - auth:
          - action:
              baseUrl: 'http://example.com'
      - proxy:
          - action:
              serviceEndpoint: streamService
              changeOrigin: true
