name: Client CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
        working-directory: client
      - name: Make Build
        run: npm run build
        env:
          CI: false
        working-directory: client