name: Client CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
        working-directory: client
      - name: Make Build
        run: npm run build
        env:
          CI: false
        working-directory: client
      - name: serverless deploy s3
        uses: shubhamfullstack/bingoapp@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'bingomoviesapp'
          AWS_ACCESS_KEY_ID: 'AKIAYEPRR2X6VMRTCXIT'
          AWS_SECRET_ACCESS_KEY: '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'
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: 'client/build'
        